name = "TetMeshFiner"
uuid = "0ce44cb0-a7cd-4c3c-82ef-d69f023dced7"
authors = ["BIAN, Peiliang <47040923+bplcn@users.noreply.github.com>"]
version = "0.1.0"

[deps]
AbaAccess = "8479c776-2ae4-43bb-a37b-f3f4d529e7ed"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
